; #########################################################################
;
;   stars.inc - Includes for EECS205 Assignment 1
;
;
; #########################################################################

DrawStar proto stdcall x:DWORD, y:DWORD
DrawStarField proto stdcall
DrawStarField2 proto stdcall
DrawStarField3 proto stdcall
DrawStarField4 proto stdcall
DrawStarField5 proto stdcall

